version: "3.8"
services:
  backend:
    container_name: backend
    build: .
    depends_on:
      - database
    environment:
      PG_USER: app_user
      PG_PASSWORD: coding_test_password
      PG_HOST: database  # Changed from localhost to database
      PG_PORT: 5432
      PG_DATABASE: datatys_db
    volumes:
      - .:/app/
    working_dir: /app
    command: npm run start
    ports:
      - "3007:3007"

  database:
    container_name: database
    image: timescale/timescaledb-postgis:latest-pg12
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: coding_test_password
      POSTGRES_DB: datatys_db
    volumes:
      - ./sql/schema.sql:/docker-entrypoint-initdb.d/1-schema.sql
      - ./sql/insert.sql:/docker-entrypoint-initdb.d/2-insert.sql
